# Google Cloud App Engine configuration
runtime: nodejs18

env_variables:
  NODE_ENV: 'production'

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 3
  target_cpu_utilization: 0.65
