# Google Cloud Build configuration for Cloud Run
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/betteraskprompt-backend', '.']
  
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/betteraskprompt-backend']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'betteraskprompt-backend'
      - '--image=gcr.io/$PROJECT_ID/betteraskprompt-backend'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-secrets=GEMINI_API_SECRET=GEMINI_API_SECRET:latest'

images:
  - 'gcr.io/$PROJECT_ID/betteraskprompt-backend'
